name: LootBags
version: 1.0
main: io.alerium.lootbags.LootBagsPlugin
authors: [Shadow Technical Systems LLC]
website: www.shadowsystems.tech
commands:
  lootbags:
    description: The command for Loot Bags.